### ISSUE TITLE
dagger非常棒呀，可是chromeDriver，IEDriver，FireFoxDriver非常不好下，你懂的，求资源！

### ISSUE THREAD

**Issue by u0mo5** [NetEase/Dagger#44]

**Comment by andrewleo** [comment]
可以在google code上selenium项目下的Downloads下载，如下链接
https://code.google.com/p/selenium/downloads/list?can=1&q=&colspec=Filename+Summary+Uploaded+ReleaseDate+Size+DownloadCount

**Comment by chenkan** [comment]
VPN大法好
