### ISSUE TITLE
maven仓库中这个com.netease.qa没有找到

### ISSUE THREAD

**Issue by goushijie** [NetEase/Dagger#47]
<dependency>
			<groupId>com.netease.qa</groupId>
			<artifactId>arrow</artifactId>
			<version>0.0.2</version>
			<scope>test</scope>
		</dependency>
这个jar在maven仓库没有找到

**Comment by MattGong** [comment]
直接找arrow项目，自己下吧

**Comment by chenkan** [comment]
可以下载这个项目 自己打成`Jar`文件 直接本地引用
https://github.com/NetEase/arrow
