### ISSUE TITLE
[Question] 失败重跑的部分在哪里啊？

### ISSUE THREAD

**Issue by yisake** [NetEase/Dagger#54]
如题，这个失败重跑应该不影响测试报告的结果吧。

**Comment by chenkan** [comment]
失败重跑是做在TestNg里面的
举个栗子：一个用例失败了，框架会自动重跑它若干次，直至成功或者依然失败；如果成功了，测试报告里面这个用例仍然算是PASS

**Comment by chenkan** [comment]
上面说的是`Dagger`最初实现的失败用例重跑方式，后来引入了`Arrow`插件来做重跑
https://github.com/NetEase/Dagger/wiki/Retry-Failed-Testcases-using-Arrow
